# This is a basic workflow that is manually triggered

name: Create host

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Enter env prefix'
        # Default value if no value is explicitly provided
        default: 'tp'
        # Input has to be provided for the workflow to run
        required: true
      protocol:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Port'
        # Default value if no value is explicitly provided
        default: 'tcp'
        options: [ 'tcp', 'udp' ]
        # Input has to be provided for the workflow to run
        required: true
      host:
          # Friendly description to be shown in the UI instead of 'name'
          description: 'Host'
          # Default value if no value is explicitly provided
          default: '8.8.8.8'
          # Input has to be provided for the workflow to run
          required: true
 
      port:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Port'
        # Default value if no value is explicitly provided
        default: '80'
        # Input has to be provided for the workflow to run
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell

    
    - name: Create dotenv
    # You may pin to the exact commit or the version.
    # uses: iamsauravsharma/create-dotenv@ace7054d9f54b5b0d2b9a4ef4853d95d4401ce7e
      uses: iamsauravsharma/create-dotenv@v1.2.2
      with:
        # Prefix for env file content
        env-prefix: ${{ github.event.inputs.name }} # optional, default is 
        # File name for env file
        file-name: .env # optional, default is .env
        # Directory for env file
        directory: . # optional, default is .
    - name: Save 
      run: |
        export URL=`${{ github.event.inputs.protocol }}://${{ github.event.inputs.host }}:${{ github.event.inputs.port }}`
        echo URL=$URL >> .env
        echo NAME=${{ github.event.inputs.name }} >> .env
        echo PROTOCOL=${{ github.event.inputs.protocol }} >> .env
        echo HOST=${{ github.event.inputs.host }} >> .env
        echo PORT=${{ github.event.inputs.port }} >> .env
        
        cat .env
